### ISSUE TITLE
Laden der verschobenen Stunden fehlerhaft

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#16]
Beispiel:

Auswahl in Settings
- WS
- Studiengang Informatik
- Semester 3 und 5
- Vorlesung Paralleles Programmieren

Commit der Daten

Ergebnis:
Beim ersten Mal werden 4 mal Änderungen geladen
Bei allen weiteren Malen nur 2  Mal Änderungen geladen (was wohl richtig ist)

Wenn man die App zweimal startet und die gleichen Einstellungen vornimmt bekommt man teilweise unterschiedliche Ergebnisse ...

**Comment by pstoehr** [comment]
Fixed

**Comment by pstoehr** [comment]
Abgleich der verlegten Stunden mit den besuchten Vorlesungen fehlt noch ...

**Comment by fuhrmann2** [comment]
Abgleichen ist eingebaut 💯
