### ISSUE TITLE
Funktion wenn Fehler beim Laden Auftritt

### ISSUE THREAD

**Issue by danielzizer** [HochschuleHofStundenplanapp/iOS-App#18]
Wenn beim laden der Daten von Server ein Fehler auftritt müssen die bereits gespeicherten Daten wieder geladen werden.
Zur Zeit werden keine Daten dargestellt obwohl ein Stundenplan erstellt wurde.

**Comment by pstoehr** [comment]
Die Anzeige des Stundenplans funktioniert bei mir auch wenn keine Netzverbindung vorhanden ist.
Bei den Stundenplanänderungen fehlt dieses Feature tatsächlich noch. Wenn man aber einen neuen Stundenplan erzeigen will (also in den Settings was verändern will), dann ist das Internet tatsächlich auch notwendig, ein Caching aller Stundenpläne der Hochschule macht auch wenig Sinn ...

**Comment by fuhrmann2** [comment]
Also die Stundenplanänderungen werden auch angezeigt, falls keine Internetverbindung vorhanden ist. Ausserdem erscheint der Alert, dass keine Internetverbindung besteht. Daran muss denke ich nichts weiter verändert werden.

**Comment by pstoehr** [comment]
Getestet
