### ISSUE TITLE
Fehler beim Laden der Stundenplanänderungen

### ISSUE THREAD

**Issue by fuhrmann2** [HochschuleHofStundenplanapp/iOS-App#20]
Nachdem die App gestartet wurde und zum ersten Mal zum Stundenplanänderungen Screen navigiert wird, werden die Daten erst geladen, wenn man auf den Settings Screen wechselt und wieder zurück zum Stundenplanänderungen Screen!

Des Weiteren tritt Gelegentlich ein "fatal error: Index out of range", beim Befüllen der Cells im Stundenplanänderungen Screen auf.

**Comment by pstoehr** [comment]
Gibt's da auch nen Stack-Trace zu?

**Comment by fuhrmann2** [comment]
Zu dem Fatal Error?

**Comment by pstoehr** [comment]
Entweder nen Stacktrace damit man weiß wo man debuggen muss oder wenigstens ein Screen Shot der etwas an Infos hergibt. 
Denn wenn der Fehler nur gelegentlich auftritt ist es schwer ihn ohne nähere Angaben zu finden.

**Comment by pstoehr** [comment]
Teil-Bugfix

Die Changes werden jetzt korrekt mit den Lectures verglichen!
