### ISSUE TITLE
SavedLectures ist leer

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/iOS-App#21]
SavedLectures ist beim klicken auf den Änderungen übernehmen Button immer leer

**Comment by danielzizer** [comment]
War ein Fehler beim laden und persistenten Speichern. Habe euren code auf savedSchedule geändert. Es funktioniert, Einträge sind im iOS Kalender zu sehen.

**Comment by GlaserDaniel** [comment]
Ah ok! Danke!
