### ISSUE TITLE
Berechnung der Änderung ist falsch

### ISSUE THREAD

**Issue by danielzizer** [HochschuleHofStundenplanapp/iOS-App#22]
Die Methoden die Brechen welche Vorlesungen hinzugefügt wurden und welche entfernt wurden liefern ein falsches Ergebnis

**Comment by danielzizer** [comment]
Methode die entfernte Vorlesungen anzeigt funktioniert

**Comment by pstoehr** [comment]
countChanges auskommentiert weil es nicht kompiliert :-(

**Comment by danielzizer** [comment]
let deleted = savedSchedule.removedLectures(oldSchedule: tmpSchedule).count
Diese Zeile bringt bei mir keine Fehler bim kompilieren.

**Comment by danielzizer** [comment]
Berechnung funktioniert nun
