### ISSUE TITLE
Vorlesungen tauchen doppelt im Kalendar auf

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#24]
1) Studiengang und Vorlesungen auswählen
2) Übernehmen wählen
3) Auswahl der Vorlesungen ändern
4) Wieder "Übernahme" wählen

--> Vorlesungen tauschen doppelt im Kalender auf

![bildschirmfoto 2016-12-14 um 17 10 51](https://cloud.githubusercontent.com/assets/14542721/21189866/48fcccb4-c220-11e6-97b7-ed2fca9a65e4.png)

**Comment by GlaserDaniel** [comment]
Ach so ja das wissen wir. Wir arbeiten noch an der Methoden die uns mitteilen welche sich geändert haben. Im Moment werden alle immer wieder reingeschrieben. Also können auch noch öfter auftauchen. 
Als info:
Wenn man den Switch mit Kalender synchronisieren aus macht und auf Änderung übernehmen klickt wird der Kalender im Moment komplett wieder gelöscht.

**Comment by pstoehr** [comment]
Aktuell taucht bei mir immer nur eine Vorlesung im Kalendar auf, obwohl mehrere in der App selektiert worden sind und auch im "Stundenplan-Screen" dargestellt werden.

**Comment by GlaserDaniel** [comment]
Das haben wir jetzt gefixt.
