### ISSUE TITLE
Studiengang könnte im Einstellungsscreen nach Wechsel zwischen SS und WS bestehen bleiben

### ISSUE THREAD

**Issue by JonasBeetz** [HochschuleHofStundenplanapp/iOS-App#27]
Der Studiengang könnte im Einstellungsscreen nach Wechsel zwischen Sommer- und Wintersemester bestehen bleiben, falls dieser weiterhin vorhanden ist.

**Comment by GlaserDaniel** [comment]
Der Studiengang bleibt bestehen, aber die Semester auch. Dadurch hat man die falschen Semester wenn man einen Studiengang auswählt und z.B. von Sommer zu Wintersemester wechselt.
Mögliche Lösung: Die Semester resetten.

**Comment by danielzizer** [comment]
Ist noch in Arbeit...

**Comment by GlaserDaniel** [comment]
Methode zum clearen der Einstellungen weil erstellt. Lectures werden bereits gecleart. Die Aufrufe für die anderen beiden müssen nur einkommentiert werden.
