### ISSUE TITLE
eventIDs werden nicht mehr gespeichert

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/iOS-App#32]
Die EventIDs werden nicht mehr gespeichert da in der init() von schedule die selLectures nun gelöscht werden. Suchen gerade nach einer Lösung.

Dadurch geht Löschen und Update im Kalender nicht mehr!

**Comment by GlaserDaniel** [comment]
Ist durch den Bugfix für Issue #25

**Comment by pstoehr** [comment]
Wo wird denn den Default Ctor für Schedule denn noch aufgerufen?
Der Copy-Ctor löscht die selLectures nämlich nicht, sie werden am Ende vom init(...) kopiert!

**Comment by sscharrer** [comment]
Haben gemeinsam mit Daniel versucht die Fehler zu finden, haben jedoch bisher keine Lösung finden können. Können Sie da eventuell mal drüberschauen ?

**Comment by pstoehr** [comment]
Wenn der Fehler besser beschrieben wird schau ich gerne mal drüber ...

Oder anders ausgedrückt: 
Wie kann ich den Fehler reproduzieren und was wäre das erwartete Ergebnis?

**Comment by GlaserDaniel** [comment]
Ich probiere hier mal das Problem etwas besser zu erklären:

Die init Methode der Schedule.swift wurde für den [Bugfix für Issue #25](https://github.com/HochschuleHofStundenplanapp/iOS-App/commit/c3e6cfcce9b49049efee179efae86cece2d0c386) folgendermaßen geändert:

init(lectures: [[Lecture]], selLectures : [Lecture]) {    
 -self.list = lectures
 -self.selLectures = selLectures
+self.list = []  
+self.selLectures = []  
+for day in lectures{  
+tmp = [  
+lecture in day{  
+append(lecture.copy() as! Lecture)  
+}  
+self.list.append(tmp)  
+}  
+for lecture in selLectures{  
+selLectures.append(lecture.copy() as! Lecture)  
+}  
}

Dadurch werden aber die EventIDs (die in der Variable eventIDs in der Klasse Lecture gespeichert werden) komischerweise gelöscht. Sie werden dafür benötigt um einzelne Event wieder aus dem Kalender zu löschen oder zu bearbeiten.

Deswegen wurde im Commit [Übergangslösung](https://github.com/HochschuleHofStundenplanapp/iOS-App/commit/c45cfb27da06152cc0993a66d68775551b79a454) der Teil erstmal wieder rückgänig gemacht.

Vielleicht funktioniert so ja auch der Bugfix für den Issue #25 trotzdem noch. Müsste man mal auch noch testen.

**Comment by pstoehr** [comment]
Ohne jetzt explizit in den Code zu schauen (ginge nur unter Lebensgefahr...) vermute ich mal dass die EventIDs das NSCopying Protokoll nicht implementieren und deswegen nicht mitkönnest werden.  

Also bitte mal nachschauen ...

**Comment by GlaserDaniel** [comment]
EventIDs sieht so aus:
var eventIDs : [String]

Also ein Array von Strings. Wie kann man da das NSCopying Protokoll implementieren?

**Comment by pstoehr** [comment]
Die Klasse in der die EventIDs gespeichert werden muss das (vermute ich mal) NSCopying implementieren (https://developer.apple.com/reference/foundation/nscopying) 

Bei der Übergangslösung wird nur eine "flache Kopie" (shallow copy) erzeugt, dass heißt es werden nur die obersten Referenzen kopiert, keine Inhalte. Das führt dazu, dass keine echten Duplikate erzeugt werden (was an der Stelle notwendig ist).
Beim Bugfix wird eine "tiefe Kopie" (Deep copy) erzeugt. Damit ein Objekt eine Deep Copy von sich und allen darin enthaltenen Teilen erzeugen kann, muss das Objekt und alle seine Teile das NScopying Protokoll implementieren. Bei der Implementierung der copy(with: Zone) Methode muss der Programmierer dann den passenden Code schreiben. Entweder es sind einfache Zuweisugen oder aber, zum Beispiel im Fall eines Arrays dass kopiert werden soll, ein Code-Block der genau dieses Kopieren übernimmt.
Fehlt irgendwo das NScopying Protokoll hört an genau dieser Stelle die Kopiererei auf!

Kommendes Jahr kann ich mal ein Blick drauf werfen (außer jemand von Ihnen macht den Bugfix)

**Comment by GlaserDaniel** [comment]
Ah ja verstanden! 😊 
In der copy Methode von Lecture muss wahrscheinlich nur noch ein .clone() an self.eventIDs angehängt werden. 
Kann ja morgen jemand machen und testen wenn er Lust hat. 😊
Und dann wieder die Init() von Schedule wieder zurück bauen. 
Falls clone nicht geht müsste man halt das Array durchgehen und dann jedes Element clonen. Oder vielleicht auch .copy().

**Comment by GlaserDaniel** [comment]
Ok. Einfach ein copy oder clone geht an einem Array anscheinend nicht. Und an ein String auch nicht. Keine Ahnung wie man dann das String Array kopiert.

**Comment by pstoehr** [comment]
Strings haben Werte-Semantik, also reicht eine einfache Zuweisen (siehe Screen-Shot)

![bildschirmfoto 2016-12-31 um 11 43 07](https://cloud.githubusercontent.com/assets/14542721/21577090/54539120-cf4e-11e6-84aa-125cf3ba9eae.png)

Bei Array ist es etwas komplizierter, die einfache Zuweisung erzeugt zwar eine weiteres Array, die Werte in dem Array werden aber "gemäß ihrer Semantik" kopiert. Wenn es ein Array of Int ist, dann erhält man tatsächliche zwei Kopien, bei einem Array of Instances werden nur die Referenzen kopiert. Für die Deep Copy muss als ein neues Array erzeugt werden und diesem neuen Array müssen dann die Kopien der Werte im anderen Array zugewiesen werden:
Code-Block aus dem Code:


+for lecture in selLectures{
+selLectures.append(lecture.copy() as! Lecture)
+}

**Comment by GlaserDaniel** [comment]
Ah ja wenn ich .copy() as! String an einen einzelnen String mache nimmt er es an. Aber funktionieren tut es immer noch nicht. Ich vermute es liegt es mehr daran das wir die eventIDs bei den tmpSchedule speichern nachdem dieser in savedSchedule kopiert wurde und dadurch sind die eventIDs dann immer leer. Also wahrscheinlich in diesem Bereich:

        let addedLectures = Settings.sharedInstance.tmpSchedule.addedLectures(oldSchedule: Settings.sharedInstance.savedSchedule)
        let removedLectures = Settings.sharedInstance.tmpSchedule.removedLectures(oldSchedule: Settings.sharedInstance.savedSchedule)
        
        Settings.sharedInstance.commitChanges() // hier wird tmp zu saved kopiert
        
        saveChangesButton.setTitle("0 Änderungen übernehmen", for: .normal)
        
        if (syncSwitch.isOn) {
            if(!addedLectures.isEmpty) {
                CalendarInterface().createAllEvents(lectures: addedLectures) // hier werden die EventIDs in den tmpSchedule gespeichert
                print("added in Calendar : \(addedLectures.count)")
            }
            if(!removedLectures.isEmpty) {
                CalendarInterface().removeAllEvents(lectures: removedLectures)
                print("removed in Calendar : \(removedLectures.count)")
            }
        }
