### ISSUE TITLE
Status des KalendarSyncSwitch persitent speichern

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/iOS-App#34]
Der KalendarSyncSwitch müsste noch persitent gespeichert werden. Wenn es unter iOS so was wie SharedPreferences gibt würde das reichen.

**Comment by pstoehr** [comment]
Ist kein größeres Problem ...

Wenn ich über Weihnachten mal Lust hab was zu programmieren baue ich es schnell ein.

**Comment by pstoehr** [comment]
Ist jetzt in den Settings gespeichert
