### ISSUE TITLE
Verweis auf Einstellungen?

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/iOS-App#35]
Wenn die App keine Berechtigung auf den Kalender hat, soll sie dann zu den Einstellungen weiterleiten?

**Comment by pstoehr** [comment]
Nein, ein Alert reicht. Und den auch bitte nur einmal solange die App aktiv ist. 
Bei jedem echten Neustart der App sollte der Alert aber wieder kommen!
