### ISSUE TITLE
Übernahme der Termine in den Kalendar fehlt

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#38]
Wenn man "Synchronisation mit Kalendar" aktiviert, werden die bereits gewählten Vorlesungen nicht in den Kalendar übernommen.

Vorgehensweise:
1) Einstellungs-Screen -> Synchronisieren mit Kalendar auf "Aus" stellen
2) Vorlesungen auswählen
3) Änderungen übernehmen
4) "Synchronisation mit Kalendar" auf "Ein" stellen
Keine Möglichkeit vorhanden die jetzt in Stundenplan abgelegten Vorlesungen in den Kalendar zu übertragen.

**Comment by GlaserDaniel** [comment]
Funktioniert jetzt wieder. Haben vorhin etwas auskommentiert.

**Comment by pstoehr** [comment]
Geht immer noch nicht!

Nach Schritt 3 sind doch alle Änderungen "übernommen". Wenn man dann die Synchronisation wieder einschaltet hat man "0 Änderungen übernehmen" im blauen Button. Wie kann man dann die Vorlesungen die ja im Stundenplan-Screen (also im ersten Tap) stehen in den iOS Kalender übernehmen?

**Comment by GlaserDaniel** [comment]
Wenn man den Switch für die Synchronisieren wieder einschaltet werden die aktuell ausgewählten Vorlesungen in den Kalender geschrieben. (ohne zutun vom Nutzer, mann muss dann nichts mehr machen, beim Button steht 0 Änderungen) 

Schauen Sie doch mal im Kalender. Die Vorlesungen müssten dann vorhanden sein. Bei uns hat es vorhin noch funktioniert.
