### ISSUE TITLE
Funktion "Alle Vorlesungen auswählen"

### ISSUE THREAD

**Issue by JonasBeetz** [HochschuleHofStundenplanapp/iOS-App#42]
Im Einstellungsscreen unter "Vorlesungen" führt der Haken rechts oben in der Ecke zu Verwirrung bei der Benutzung. Viele denken dieser dient als Bestätigungsbutton und nicht als "alle Vorlesungen auswählen" Button

Lösungsvorschlag:
Kleines Popupmenü (angedeutet mit 3 kleinen Punkten), welches den Menüpunkt "Alle auswählen" bzw. "alle abwählen" beinhaltet.

**Comment by pstoehr** [comment]
Oder wir machen einen Rahmen ums Häkchen. Und für "nicht selektiert" machen wir ein gehighlightedes Häkchen rein ...

Aber ich bin da leidenschaftslos!
