### ISSUE TITLE
Vorlesungen bleiben im Stundenplan der App, auch wenn das Semester abgewählt wird

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#45]
**Beschreibung**
In der App wird ein Studiengang und mehrere Semester gewählt. In den Semestern werden jeweils Vorlesungen selektiert. 
Wenn man diesen Stundenplan übernimmt hat man Vorlesungen aus mehreren Semestern in dem Kalendar der App. Wenn man nun ein Semester in den Settings abwählt, bleiben die Vorlesungen im Kalender der App.

**Testbeispiel**
1. Wintersemester, Studiengang Informatik und Semester 3 und 5 wählen
2. Jeweils mindestens eine Vorlesung aus dem 3 und dem 5 Semester wählen
3. Kalender synchronisieren
4. Im Stundenplan sind nun Vorlesungen aus dem 3 und 5 Semester
5. Semester 5 "abwählen"
6. Synchroniseren (obwohl da 0 Änderungen übernehmen steht)
7. Vorlesungen des 5. Semesters sind immer noch im Stundenplan der App

**Erwartetes Ergebnis**
Vorlesungen des nicht mehr selektierten Semesters werden gelöscht sobald man auf "Synchroisieren" drückt und die Anzahl der Änderungen ist != 0

**Tatsächliches Ergebnis**
Vorlesungen des nicht mehr selektierten Semesters sind noch vorhanden

**Comment by danielzizer** [comment]
Das selbe passiert auch wenn man ein Studiengang abwählt. Die Vorlesungen des abgewählten Studiengangs werden im Stundenplan immer noch angezeigt.

**Comment by danielzizer** [comment]
Müssten wir dann nicht zu jedem Studiengang die zugehörigen Vorlesungen abspeichern? Und zu jedem Studienhang->Semester alle zugehörigen Vorlesungen?
