### ISSUE TITLE
Einzeltermine

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/iOS-App#49]
Wenn es Vorlesungen die Einzeltermine sind (also zum Beispiel nur 4 Mal im Semester an gewissen Tagen stattfinden) werden sie im Moment noch so angezeigt als wären sie jede Woche.

Zum Beispiel:
MC 6 Onlinemarketing ist 4 mal Freitag und 4 mal Samstag

Mögliche Lösung:
Bei diesen Vorlesungen müsste man auf das Start und Enddatum schauen. Wenn das gleich ist findet die Vorlesung nur an einem Tag und zwar diesem statt.

**Comment by GlaserDaniel** [comment]
Der Fehler ist auch schon in dem Stundenplan in der App. Wir kriegen die Vorlesungen so.

**Comment by pstoehr** [comment]
Okay, dann ein reassign ...
