### ISSUE TITLE
Zeitumstellung

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/iOS-App#50]
Wenn man in der alten Zeit den Stundenplan anlegt und darin Vorlesungen für die neue Zeit sind, sind diese Vorlesungen in der neuen Zeit um eine Stunden verschoben. 

Die Zeiten müssten sich anpassen wenn man den Stundenplan löscht und wieder neu anlegt in der neuen Zeit. Aber lieber noch mal testen.

**Comment by pstoehr** [comment]
Das ist aber sicherlich nicht die Lösung, oder?

**Comment by GlaserDaniel** [comment]
Nein aber vorübergehen müsste es so gehen.
Wir müssten da irgendwie bei den Zeiten schauen das die wissen ob Sommer oder Winterzeit ist. Also das Problem ist das wir da immer 7 Tage dazu rechnen zu dem Datum. Und das Datum da anscheinend nicht selbst bemerkt das es dann auch mal in eine neue Zeit rutschen kann. 
Oder es bemerkt es und verschiebt die Zeit deswegen um eine Stunde. 
Kann aber auch am Kalender liegen.

Da müssen wir noch mal schauen.

**Comment by pstoehr** [comment]
Achja, die Berechnungen der Zeiten in CalenderInterface ...

Wenn man es, so wie von mir vorgeschlagen, nicht direkt sondern über die Calendar-Klasse macht klappt es. Siehe Screen-Shot

![bildschirmfoto 2017-02-09 um 13 01 08](https://cloud.githubusercontent.com/assets/14542721/22782568/0236aca8-eec8-11e6-9331-e50c44648a69.png)

**Comment by GlaserDaniel** [comment]
Ah ok. Hab's ausgetauscht. Passt jetzt. Danke!

**Comment by pstoehr** [comment]
Da sind doch immer noch Berechnungen von Zeiten die direkt und **nicht** über Calendar gemacht werden!

**Comment by GlaserDaniel** [comment]
Ok. So dann oder?
Bei Changes hab es noch auskommentiert gelassen weil man da erst noch testen muss ob da jetzt auch was mit einer Stunde verschoben nicht passt oder nicht.

**Comment by pstoehr** [comment]
Scheint zu passen ...
