### ISSUE TITLE
Daten des aktuellen Sommersemesters werden nicht in die Kalendar.App übertragen

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#51]
Wenn man aktuell einen Stundenplan für das Sommersemester 2017 erstellt werden die Daten **nicht** in die Kalendar.App übernommen!

**Comment by pstoehr** [comment]
Tritt aktuell nicht mehr auf ...

Womöglich ist da noch ein Fehler bei der Bestimmung des ersten Tages des Semesters drin ...

**Comment by PaulForstner** [comment]
Ich hab den Anfang und das Ende angepasst. Bisher war es so, dass das nächste Semester nach der Prüfungszeit angefangen hat. Ich hab es jetzt so verändert, das es mit der Prüfungszeit anfängt, also nachdem die Vorlesungen des vorherigen Semesters zu Ende sind.

**Comment by pstoehr** [comment]
Fixed
