### ISSUE TITLE
Absturz beim Vergeben Zugriffsrechte 

### ISSUE THREAD

**Issue by danielzizer** [HochschuleHofStundenplanapp/iOS-App#52]
Installiert man die neue Version und legt einen Stundenplan an und klickt auf Änderungen übernehmen. Im popul den zugrifff auf den kalender verweigern. -> die app hängt sich auf und stürzt ab

**Comment by pstoehr** [comment]
Bei der aktuellen Version aus dem App-Store (Version 1.01 vom 16.02.) hab ich die Synchronisation abgeschälten.
Die Bugs hab ich leidlich gefixt (siehe Development-Branch), ne neue Version gebaut und zur Valdierung im APP-Store hochgeladen.

**Comment by pstoehr** [comment]
Fixed im Development-Branch
