### ISSUE TITLE
Stürzt nach Update ab

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/iOS-App#53]
Die App stürzt nach dem Update vom 24.2 und nach dem Update von heute (6.3) sofort beim Start ab.

Eine Neuinstallation scheint zu helfen. Aber es sollte eigentlich auch zu Updaten funktionieren.

Ich weiß noch nicht ob es mit der Berechtigung für den Kalender zu tun hat oder nicht.

Mir haben das nur welche geschrieben. Also noch nicht selbst getestet. Hat jemand die selbe Erfahrung gemacht?

**Comment by pstoehr** [comment]
In der ersten Version war ein paar richtig fiese Fehler drin. Bei zweien ist es so, dass sie, sobald man eine neuere Variante einspielt, beim ersten Start der App crashes. Das zu fixen war mir einfach zu viel Arbeit!
Nach diesem ersten Crash läuft die App aber, so lang sich der Server benimmt, stabil.

Viele Grüße 
    Peter Stöhr

**Comment by GlaserDaniel** [comment]
Also ich hab einen nochmal gefragt ob die App beim zweiten Versuch dann funktioniert. Aber er meinte nein, sie stürzt immer ab. Neu installieren will er sie nicht da er den Stundenplan nicht neu anlegen will. Er will mir noch ein Video aufnehmen und zeigen wie es passiert.

**Comment by GlaserDaniel** [comment]
Ok. Hier das Video: https://goo.gl/photos/e4KzJZfhHkvRsXCq9
Es kommt anscheinend keine Fehlermeldung.

**Comment by pstoehr** [comment]
Er soll einfach mal die Daten synchronisieren!
Der Fehler in den Zugriffsrechten für den Kalender und ein Fehler beim Schreiben der Daten führt dazu, dass unter Umständen eine "inkonsistente" Version der Versionierungsinfo geschrieben wird.

Um den Bug zu fixen müsste man jetzt entweder in der App den Binärinhalt der Versionierungsinfo analysieren, diesen Fall entdecken und dann drauf reagieren. Dazu hatte ich ehrlich gesagt weder Zeit noch Lust!

Alternativen sind:
1) App löschen und neuistallieren
2) Die Daten einfach einmal rausschreiben, dann sollte es funktionieren!
