### ISSUE TITLE
Fehler bei der Uhrzeit

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#54]
Wenn man, nach Beginn der Sommerzeit, Termine in den Kalender übernimmt wird die Zeit falsch überNommen :-(

**Comment by krrtDe** [comment]
Übernimmt er ab der Sommerzeit jeden Termin falsch oder nur den ersten Tag?

An meinem Device wird nur der heutige Tag falsch synchronisiert (siehe Bild).

![bild](https://cloud.githubusercontent.com/assets/20622736/24343110/038d1ab2-12c5-11e7-9867-4c0b4d25a3b6.png)

**Comment by pstoehr** [comment]
Der Fehler liegt wohl daran, dass bei den Zeiten im Schedule-Objekt nur die Uhrzeit, nicht aber das Datum gesetzt werden.
Wenn man die Startzeit aus dem String "09:45" erzeugt, dann wird die Uhrzeit für den 1.1.2000 bestimmt. Damit hat liegt Uhrzeit immer in der CET. Beim Startdate wird aber entweder der erste passende Wochentag oder das aktuelle Datum verwendet.
Seit Sonntag liegt dieses Datum in der CEST. Kombiniert man jetzt diese beiden Zeitpunkt während der Normalzeit passt es, seit Sonntag läuft dass aber auseinander.

Quickfix: 
Beim Start- und Enddatum wird jetzt immer der erste Termin im Semester verwendet. Das klappt so aber nur im SS.

**Bitte testen und bis zum Nachmittag melden ob es so passt**

Für Version 2:
Die vom Server kommende, recht dödlige Aufteilung der Zeitpunkte in Datum und Uhrzeit wird aufgehoben. StartDate und EndDate in Schedule enthalten dann immer den vollständigen Zeitpunkt! Zugriff auf die Teilkomponenten dann über entsprechende Zugriffsfunktionen!

**Comment by sscharrer** [comment]
Montag bis Mittwoch ist bei mir weiterhin um eine Stunde verschoben. Von Donnerstag bis Samstag befinden sich die Vorlesungen an der richtigen Stelle.

Vor Ihrem Buxfix waren bei mir alle Vorlesungen, bis auf die am Donnertag, um eine Stunde verschoben. 

<img width="374" alt="bildschirmfoto 2017-03-27 um 10 55 08" src="https://cloud.githubusercontent.com/assets/22611742/24348418/f41e77a8-12db-11e7-9fac-5b05cf42dcf0.png">

**Comment by sscharrer** [comment]
Habs jetzt nochmal an paar anderen Geräten (Simulator) getestet. Jetzt scheint alles zu funktionieren.

<img width="462" alt="bildschirmfoto 2017-03-27 um 11 37 28" src="https://cloud.githubusercontent.com/assets/22611742/24350250/d0e24408-12e1-11e7-8a8d-ebf020a56505.png">

**Comment by svenrill** [comment]
Ich habe es auf meinem iPhone getestet. Die Zeiten sind so korrekt.
Allerdings muss die Kalendersynchronisation deaktiviert/aktiviert werden, da sonst alle bereits im Kalender eingetragenen Termine mit der falschen Uhrzeit enthalten sind (werden ja nicht aktualisiert).
