### ISSUE TITLE
Sortierung der USerData-Einträge muss noch angepasst werden

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#55]
Wer ist denn für die passende Sortierung der Daten in dem UserData-Objekt verantwortlich?
Aktuell spiegelt die Reihenfolge in den Arrays ja die Reihenfolge der Clicks wider.

**Comment by danielzizer** [comment]
also aktuell werden die Arrays in UserData noch nicht sortiert. Wie soll dann sortiert werden?

**Comment by pstoehr** [comment]
Ahoi,

die spannende Frage ist eher, ob die Sortierung im Modell für alle gemacht wird, oder ob die Aufgabe an den passenden Controller delegiert wird.

Einen schönen Abend noch
    Peter Stöhr

> Am 16.05.2017 um 18:34 schrieb danielzizer <notifications@github.com>:
> 
> also aktuell werden die Arrays in UserData noch nicht sortiert. Wie soll dann sortiert werden?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
Prof. Dr. Peter Stöhr
Alfons-Goppel-Platz 1; 95028 Hof (Germany)
Fon: 0049 - 9281 - 409 4850

**Comment by pstoehr** [comment]
Sortierung im Model schein doch cleverer zu sein. Dann passt es nämlich auch für die nachfolgenden Screens ...
