### ISSUE TITLE
Arbeiten mit "Kopien"

### ISSUE THREAD

**Issue by danielzizer** [HochschuleHofStundenplanapp/iOS-App#56]
Aktuell ist es so das die top Zugriffsschichten im SettingsTableViewController erzeugt werden und dann an die weiteren Screens weitergegeben werden. Nun müssen ja die Zugriffsschichten auf einer Kopie der Daten arbeiten. Geplant war es diese Kopien in der Init der Schichten zu erzeugen. 

Problem:
Nun ist es so das zwei Zugriffsschichten ein und die selbe Kopie eine Selected Objektes brauchen.
Das bedeutet das die Kopie vor der Erzeugung der Schichten erstellt werden muss, welche dann an die Init der Schichten mitübergeben werden muss.

Wäre es nicht sinnvoller im Singelton UserData zu jedem Selected Array ein TmpSelekted Array hinzuzufügen? Auf dieses kann dann überall zugegriffen werden. Ich finde das Weiterreichen der Daten wir jetzt langsam unübersichtlich

**Comment by pstoehr** [comment]
Im Prinzip ja, aber ...
Das „Problem“ ist, wer ist Owner der einzelnen Daten. Aktuell ist es so, dass der Settings-Controller diese Ownership auf die dahinterlkegenden Controller delegiert. Das klappt aber aktuell wohl nicht.
Die Idee mit den zusätzlichen selected-Arrays ist naheliegend und verlockend, aber dann landen wir über kurz oder lang wieder beim alten Design ...
Das weiterreichen der Daten ist zwar dezent aufwendiger (2 Variable pro Controller), die Frage des Ownership erscheint mir dann aber klarer geklärt zu sein.

**Comment by danielzizer** [comment]
Könnte man nicht dem SettingsController die drei Sichten zuweisen, welcher dann zuständig ist die Kopien zu erstellen und diese den Schichten zu übergeben? Nun müssten wir jedem hinterlegenden Screen nur den SettingsController übergeben.
