### ISSUE TITLE
Duplikate bei Auswahl der Vorlesungen (Settings Screen)

### ISSUE THREAD

**Issue by wolf-code-de** [HochschuleHofStundenplanapp/iOS-App#57]
Beim Studiengang BBB (Berufsbegleitender Bachelor Betriebswirtschaft SP ....) kommen im Semester 4 Duplikate vor bei der Auswahl der Vorlesungen im Settings Screen. 
![bildschirmfoto 2017-06-22 um 12 06 28](https://user-images.githubusercontent.com/20622938/27428732-47175794-5743-11e7-9463-ccffa4fd9731.png)

**Comment by wolf-code-de** [comment]
weiterer Fall: InnoTex Semester 6
![bildschirmfoto 2017-06-22 um 12 58 59](https://user-images.githubusercontent.com/20622938/27430911-a9cea1ec-574a-11e7-8422-d457b8c483f4.png)

**Comment by fuhrmann2** [comment]
Fixed
