### ISSUE TITLE
"Entfällt wegen Erkrankung" Meldung

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#65]
Wenn kein Ersatztermin bei einer Verlegung vorhanden ist, wird wohl immer der Text "Entfällt wegen Erkrankung" angezeigt. 
Hier sollte/muss das "reason" Element des JSON-Objekts in das Model übernommen werden und dann ausgewertet werden. Danach kann man eine passendere Meldung ausgeben.

Einstiegspunkte:
   JSONChanges.swift
   ChangedLecture.swift
   ScheduleChanges/

**Comment by svenrill** [comment]
mit neuer AppStore-Version behoben
