### ISSUE TITLE
Fehler bei Stundenplanänderungen

### ISSUE THREAD

**Issue by pstoehr** [HochschuleHofStundenplanapp/iOS-App#69]
Daten bei Stundenplanänderungen werden teilweise falsch übernommen.
Beispiel:
MC 1 - Alle Vorlesungen auswählen und übernehmen
![bildschirmfoto 2017-10-24 um 16 18 16](https://user-images.githubusercontent.com/14542721/31948576-925aab48-b8d7-11e7-9331-95e958603f14.png)

**Comment by GlaserDaniel** [comment]
Das ist ein Problem der Schnittstelle: https://github.com/HochschuleHofStundenplanapp/Schnittstelle/issues/10

**Comment by svenrill** [comment]
Wird mit https://github.com/HochschuleHofStundenplanapp/iOS-App/issues/72 umgesetzt.
