### ISSUE TITLE
UI API called from background thread

### ISSUE THREAD

**Issue by cpfeiffer94** [HochschuleHofStundenplanapp/iOS-App#70]
Im SettingsTableViewController wird in der Methode: saveChangesButton() der changesButton von einem nicht UIThread aufgerufen, was zu einer Exception führt (und dass der Button beim Betätigen von "xx Änderungen übernehmen" unsichtbar wird). 

Auch die Methode stopActivityIndicater() in der Klasse ActivityIndicater wird von einem Hintergrundthread aufgerufen. (verschwindet aber trotzdem).

**Comment by Marceeelll** [comment]
Haben den Bug heute entfernt, haben es nur noch nicht gepusht, weil dadurch ein anderer Fehler aufgetauchten ist, der von unseren Vorgängern mit Notifications umgangen wurde. Pushen sobald beide Bugs entfernt wurden :)
