### ISSUE TITLE
Ergänzung um Feld "text" (v4)

### ISSUE THREAD

**Issue by svenrill** [HochschuleHofStundenplanapp/iOS-App#72]
Das Feld "text" wurde bisher nicht über die Schnittstelle bereitgestellt, enthält aber relevante Informationen für eine "nicht normale" Stundenplanänderung. Bisher wird der Inhalt nur auf der Webseite rot dargestellt.
Sobald das Feld in der Schnittstelle aufgenommen wurde (https://github.com/HochschuleHofStundenplanapp/Schnittstelle/issues/12), soll dies in die App wie besprochen übernommen werden.

**Comment by cpfeiffer94** [comment]
Das Feld text wird seit heute in Schnittstellenversion 3.5 bereitgestellt und kann ausgewertet werden.

**Comment by svenrill** [comment]
in v3.2 enthalten
in v4 fehlt noch die Anpassung der Kalendereinträge (Titel und Notiz) analog v3.2

**Comment by svenrill** [comment]
in v4 ergänzt
