### ISSUE TITLE
Probleme bei der Zusammenarbeit der Kalendersynchronisation mit dem Framework

### ISSUE THREAD

**Issue by cpfeiffer94** [HochschuleHofStundenplanapp/iOS-App#81]
Wenn die Kalendersynchronisation aktiviert ist, dann stürzt die App beim Screenwechsel ab.
Eventuell ist der CalenderController mit der Lecture Klasse aus dem Framework inkompatibel.

<img width="809" alt="bildschirmfoto 2018-01-08 um 15 49 01" src="https://user-images.githubusercontent.com/22813839/34675984-865a7b9e-f48b-11e7-84e0-864c04b6e120.png">
Screenshot aus der Klasse Lecture
<img width="428" alt="bildschirmfoto 2018-01-08 um 15 48 44" src="https://user-images.githubusercontent.com/22813839/34675986-8834203c-f48b-11e7-9a3e-00f0dd93024b.png">
Die Auftretende Exception

**Comment by pstoehr** [comment]
Nicht nur „eventuell“ ...
Der Cast versucht aus einem ChangedLecture Object ein Lecture Object zu machen. Da knallt es halt!

**Comment by svenrill** [comment]
Es wurde die "falsche" isEqual() verwendet, korrigiert mit [1da9eb3](https://github.com/HochschuleHofStundenplanapp/iOS-App/commit/1da9eb318f5f66eb7e1be03409b1095c81b23967) ... ;-)
